spring:
  application:
    name: realwinner

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
